/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelinhas;

import daos.JogadorDao;
import daos.PersonagemDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jogo.Personagem;
import usuario.Jogador;

/**
 *
 * @author AlexaLins
 */
public class UsuarioOpcao extends javax.swing.JFrame {
    JogadorDao dao = null;
    PersonagemDao daop =null;
    /**s
     * Creates new form UsuarioOpcao
     */
    public UsuarioOpcao() throws Exception {
        dao = new JogadorDao();
        daop = new PersonagemDao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("League of Legends");
        getContentPane().setLayout(null);

        jButton1.setText("Ver todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 73, 80, 40);

        jButton2.setText("Campeão");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 70, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AlexaLins\\Documents\\NetBeansProjects\\LoLzin\\lolicon.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 200);

        setSize(new java.awt.Dimension(365, 210));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Personagem> personagem = null;
        
        try {
            personagem  = daop.list();
        } catch (SQLException ex) {
            Logger.getLogger(AdmOpcao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String titulos [] = {"Nome","Descrição"};
        if (personagem!= null){
            String [][] matriz = new String [personagem.size()][6];
            for (int i = 0; i < personagem.size(); i++){
                Personagem p = personagem.get(i);
                matriz[i][0] = p.getNome();
                matriz[i][1] = p.getDes();
            }
        
            
            
        DefaultTableModel modelo = new DefaultTableModel(matriz, titulos);
        
       MaisPersonagem novo = null;
            try {
              novo = new MaisPersonagem();
            } catch (Exception ex) {
                Logger.getLogger(AdmOpcao.class.getName()).log(Level.SEVERE, null, ex);
            }
        novo.setVisible(true);
        novo.alteraTabela(modelo);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        List<Personagem> personagem = null;
        
        try {
            int ultimo = dao.ultimoId();
            Jogador jogador = new Jogador(ultimo);
            jogador.setId(ultimo);
            
            personagem  = dao.listP(jogador);
            
        } catch (SQLException ex) {
            Logger.getLogger(AdmOpcao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String titulos [] = {"Nome","Descrição"};
        if (personagem!= null){
            String [][] matriz = new String [personagem.size()][6];
            for (int i = 0; i < personagem.size(); i++){
                Personagem p = personagem.get(i);
                matriz[i][0] = p.getNome();
                matriz[i][1] = p.getDes();
            }
        
            
            
       DefaultTableModel modelo = new DefaultTableModel(matriz, titulos);
        
       TelaJogador novo = null;
            try {
              novo = new TelaJogador();
            } catch (Exception ex) {
                Logger.getLogger(AdmOpcao.class.getName()).log(Level.SEVERE, null, ex);
            }
        novo.setVisible(true);
        novo.alteraTabela(modelo);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UsuarioOpcao().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(UsuarioOpcao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
